server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
      #server-addr: localhost:8848 #配置Nacos地址
      #换成nginx的1111接口，做集群
        server-addr: 192.168.192.5:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'



